Document source
profcomff/print-webapp pull request #33
Opened 2023-07-28 14:02 UTC by Temmmmmo

## Изменения
При отправке документа на печать также передается поле с источником отправки.

## Реализации
Добавлено поле source в модель, отправляемую на ручку. 

## Детали
Добавленное поле `source` имеет значение `webapp` и отправляется при отправке post-запроса `/file` в [**print-api**](https://github.com/profcomff/print-api)

## Check-List
- [x] Вы проверили свой код перед отправкой запроса? 
- [x] Вы написали тесты к реализованным функциям? - **не требуется**
- [x] Вы не забыли применить black и isort? - **не требуется**

2023-08-10 10:00 UTC, physphile requested changes

2023-08-10 10:00 UTC, physphile commented on src/components/SendTaskDialog.vue
> +      source: "webapp",
тут не нужно, оставь только в теле запроса

2023-08-11 11:27 UTC, dyakovri commented on src/components/SendTaskDialog.vue
> +          source: this.source,
А где определено this.source? Я думал это должна быть константа, не?

2023-08-11 13:06 UTC, dyakovri approved these changes

2023-08-11 13:08 UTC, merged